###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  mysql:
    image: mysql:5.6
    container_name: scrum-tools-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpw
      - MYSQL_DATABASE=scrumtools
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: scrum-tools-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8000:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: scrum-tools-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  nodejs:
    image: node:8.11.1
    container_name: scrum-tools-nodejs
    working_dir: /application
    volumes:
      - .:/application
